---
- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodejs 16.x repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: git clone market-cms
  git:
    repo: https://github.com/medienhaus/medienhaus-cms
    #repo: git@github.com:medienhaus/medienhaus-cms.git
    dest: /opt/market-cms
    force: yes
    update: yes
    version: market
    #key_file: /root/.ssh/id_rsa
    #accept_hostkey: yes

- name: configure market-cms
  template:
    src: .env
    dest: /opt/market-cms/.env
    owner: root
    group: root
    mode: 0644

- name: install requirements via package.json
  command: npm clean-install
  args:
    chdir: /opt/market-cms

- name: build market-cms
  command: npm run build
  args:
    chdir: /opt/market-cms

- name: sync /opt/market-cms/build/ with /var/www/market_cms_endpoint
  command: "rsync -avvr --delete /opt/market-cms/build/ /var/www/{{ market_cms_endpoint | default('market-cms') }}"
  notify: restart nginx
