password_providers:
  - module: "ldap_auth_provider.LdapAuthProvider"
    config:
      enabled: true
{% if synapse_ldap_bind_dn %}
      mode: "search"
{% endif %}
      uri: "{{ synapse_ldap_uri }}"
      start_tls: false
      base: "{{ synapse_ldap_base }}"
      attributes:
        uid: "{{ synapse_ldap_attribute_uid }}"
        mail: "{{ synapse_ldap_attribute_mail }}"
        name: "{{ synapse_ldap_attribute_name }}"
{% if synapse_ldap_bind_dn %}
      bind_dn: "{{ synapse_ldap_bind_dn }}"
      bind_password: "{{ synapse_ldap_bind_password }}"
{% endif %}
