password_providers:
  - module: "ldap_auth_provider.LdapAuthProvider"
    config:
      enabled: true
      mode: "search"
      uri: "{{ synapse_ldap_uri if (inventory_hostname_short == 'medienhaus') else synapse_ldap_proxy }}"
      start_tls: true
      base: "{{ synapse_ldap_base }}"
      attributes:
        uid: "{{ synapse_ldap_attribute_uid }}"
        mail: "{{ synapse_ldap_attribute_mail }}"
        name: "{{ synapse_ldap_attribute_name }}"
      bind_dn: "{{ synapse_ldap_bind_dn }}"
      bind_password: "{{ synapse_ldap_bind_password }}"
      #filter: "(objectClass=posixAccount)"
