---
- name: install packages for unattended-upgrades
  apt:
    name:
      - apt-listchanges
      - unattended-upgrades
    state: latest
  notify: start unattended-upgrades

- name: configure mail address
  lineinfile:
    path: /etc/apt/listchanges.conf
    regexp: '^email_address='
    line: 'email_address={{ admin_contact }}'
  notify: restart unattended-upgrades

- name: configure mail address
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^(?://)?Unattended-Upgrade::Mail '
    line: 'Unattended-Upgrade::Mail "{{ admin_contact }}";'
  notify: restart unattended-upgrades

- name: configure automatic reboots
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^(?://)?Unattended-Upgrade::Automatic-Reboot '
    line: 'Unattended-Upgrade::Automatic-Reboot "true";'
  notify: restart unattended-upgrades
