---
- name: install, configure, and start spaces stack
  hosts: spaces
  roles:
    - roles/common
    - roles/nginx
    - roles/element-web
    - roles/medienhaus-frontend
    - roles/medienhaus-cms
  vars:
    nginx_site: spaces
    element_web_root: classroom
    element_web_version: v1.7.33
